networks:
  daily-report:
    driver: bridge

volumes:
  logs-data:
  history-data:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    volumes:
      - logs-data:/var/www/html/logs
      - history-data:/var/www/html/history
    networks:
      - daily-report
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "${DAILY_REPORT_PORT:-8081}:80"
    networks:
      - daily-report
    depends_on:
      php:
        condition: service_healthy
    restart: unless-stopped
